# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c49c32423a5f97fa592e191feed914dde537405d3a8bd256abf294a51da70024e023313d1da3dce19dea032e0a40db8c99562fdd17f29f68b3a6a56d26c49d8d

test:
  secret_key_base: e182510b234be51fb973ab6c17107800fb1fd3f36b4c2e3f62d6e1fc45bd1e32c6316c7a58c9a542d3c23c780e0bb15502bc5273273c6208f51f153acda0093f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
